name: Build, Scan
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build-and-push:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Docker Login to ACR
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login octaacrtestng.azurecr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
        - name: Build Docker Image
          run: docker build -t octaacrtestng.azurecr.io/myapptest:${{ github.sha }} .
    
        - name: Push Docker Image
          run: docker push octaacrtestng.azurecr.io/myapptest:${{ github.sha }}

  deploy-aks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: octa-aks
          resource-group: octa-aks-rg # ✅ Change if different

      - name: Update Deployment Image
        run: |
            kubectl apply -f manifest/
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/my-app my-app=octaacrtestng.azurecr.io/my-app:${{ github.sha }} -n default
          

      # - name: Apply other manifest files (if needed)
      #   run: |
      #     kubectl apply -f manifest/
